# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountpage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 372)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(20, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.namefield = QtWidgets.QLineEdit(self.centralwidget)
        self.namefield.setGeometry(QtCore.QRect(170, 40, 371, 31))
        self.namefield.setObjectName("namefield")
        self.dob = QtWidgets.QLabel(self.centralwidget)
        self.dob.setGeometry(QtCore.QRect(20, 100, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dob.setFont(font)
        self.dob.setObjectName("dob")
        self.AccountNumber = QtWidgets.QLabel(self.centralwidget)
        self.AccountNumber.setGeometry(QtCore.QRect(20, 150, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AccountNumber.setFont(font)
        self.AccountNumber.setObjectName("AccountNumber")
        self.accnumfield1 = QtWidgets.QLineEdit(self.centralwidget)
        self.accnumfield1.setGeometry(QtCore.QRect(170, 140, 161, 31))
        self.accnumfield1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.accnumfield1.setMaxLength(8)
        self.accnumfield1.setCursorPosition(8)
        self.accnumfield1.setObjectName("accnumfield1")
        self.accnumfield2 = QtWidgets.QLineEdit(self.centralwidget)
        self.accnumfield2.setGeometry(QtCore.QRect(380, 140, 161, 31))
        self.accnumfield2.setMaxLength(8)
        self.accnumfield2.setObjectName("accnumfield2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 140, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Balance = QtWidgets.QLabel(self.centralwidget)
        self.Balance.setGeometry(QtCore.QRect(20, 200, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Balance.setFont(font)
        self.Balance.setObjectName("Balance")
        self.balancefield = QtWidgets.QLineEdit(self.centralwidget)
        self.balancefield.setGeometry(QtCore.QRect(170, 190, 371, 31))
        self.balancefield.setObjectName("balancefield")
        self.btnDone = QtWidgets.QPushButton(self.centralwidget)
        self.btnDone.setGeometry(QtCore.QRect(280, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDone.setFont(font)
        self.btnDone.setObjectName("btnDone")
        self.account_id_field = QtWidgets.QLineEdit(self.centralwidget)
        self.account_id_field.setGeometry(QtCore.QRect(170, 240, 371, 31))
        self.account_id_field.setText("")
        self.account_id_field.setReadOnly(True)
        self.account_id_field.setObjectName("account_id_field")
        self.acc_id = QtWidgets.QLabel(self.centralwidget)
        self.acc_id.setGeometry(QtCore.QRect(20, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acc_id.setFont(font)
        self.acc_id.setObjectName("acc_id")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 91, 371, 31))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Account Page"))
        self.name.setText(_translate("MainWindow", "Name:"))
        self.dob.setText(_translate("MainWindow", "Date of Birth:"))
        self.AccountNumber.setText(_translate("MainWindow", "Account Number:"))
        self.accnumfield1.setInputMask(_translate("MainWindow", "00000009"))
        self.accnumfield2.setInputMask(_translate("MainWindow", "00000009"))
        self.label_5.setText(_translate("MainWindow", "-"))
        self.Balance.setText(_translate("MainWindow", "Balance:"))
        self.balancefield.setInputMask(_translate("MainWindow", "0000000009"))
        self.btnDone.setText(_translate("MainWindow", "Done"))
        self.account_id_field.setPlaceholderText(_translate("MainWindow", "Filled in Automatically"))
        self.acc_id.setText(_translate("MainWindow", "Account ID:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
